### ISSUE TITLE
Error while no prompts saved.

### ISSUE THREAD

**Issue by alexandersokol** [namkazt/sd-webui-prompt-history#9]
Hello again, just noticed when I added an extension to the fresh sd setup, that there is an error on the `Prompt History` tab and error gone only when I'm generated first image and restarted sd.

**Comment by namkazt** [comment]
thanks, i will check on that issue

**Comment by alexandersokol** [comment]
yep, here is it:
```
Traceback (most recent call last):
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 633, in continuous_fn
    output = fn(*args)
  File "D:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-prompt-history\scripts\prompt_history_script.py", line 339, in history_table
    <a href="#" class="g-actions-button g-actions-button-pager" onclick={on_click_prev_fn}>◀️ Prev</a>
UnboundLocalError: local variable 'on_click_prev_fn' referenced before assignment
Task exception was never retrieved
future: <Task finished name='amgdycywc1g_218' coro=<Queue.process_events() done, defined at D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\queueing.py:343> exception=ValueError('[<gradio.queueing.Event object at 0x0000018B5C3C2140>] is not in list')>
Traceback (most recent call last):
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\queueing.py", line 432, in process_events
    self.active_jobs[self.active_jobs.index(events)] = None
ValueError: [<gradio.queueing.Event object at 0x0000018B5C3C2140>] is not in list
```
